services:
  - type: web
    name: inter-veterano
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: chave-secreta
      - key: SQLALCHEMY_DATABASE_URI
        value: mysql+pymysql://admin:Intervet2025@intervetdb.cep6qq66kx3j.us-east-1.rds.amazonaws.com:3306/intervetdb

