services:
  - type: web
    name: inter-veterano
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: DATABASE_URL
        value: mysql+pymysql://rena1558_interadmin:Intervet2025@interveterano.com/rena1558_intervetdb
      - key: SECRET_KEY
        value: chave-secreta
